version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
  - dependency-name: gatsby
    versions:
    - 2.32.8
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.16.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.13.0
  - dependency-name: stylelint
    versions:
    - 13.11.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: typescript
    versions:
    - 4.2.2
