[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[build]
  base = "blog"
  command = "yarn build"
  publish = "public"
[build.environment]
  YARN_VERSION = "1.22.5"
  NODE_VERSION = "14"
  YARN_FLAGS = "--no-ignore-optional"
  NETLIFY_USE_YARN = "true"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
  Content-Security-Policy = "default-src 'self'; script-src www.google-analytics.com 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src data: www.google-analytics.com stats.g.doubleclick.net 'self'; font-src 'self'; form-action 'self'; connect-src 'self' www.google-analytics.com stats.g.doubleclick.net"