[build]
  publish = "public/"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Feature-Policy = "vibrate none; geolocation none; unsized-media none;"
    Content-Security-Policy = "default-src 'self'; script-src * blob: data: 'self' 'unsafe-inline' 'unsafe-eval' ;style-src 'self' 'unsafe-inline'; img-src data: 'self' *; font-src data: 'self';connect-src 'self'; object-src 'none'; form-action 'self'; child-src 'self'; frame-ancestors 'self';frame-src 'self'; worker-src blob;"