name: Lighthouse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node Modules
      run: yarn

    - name: Build
      run: |
        yarn build

    - name: Lighthouse
      run: |
        yarn test:lh:ci --url=http://localhost:9000/using-wpp-targets-file-together-sitecore/
        yarn test:lh:assert
  
    - name: Archive Lighthouse results
      uses: actions/upload-artifact@v1
      with:
        name: lighthouse-report
        path: .lighthouseci

    - name: Lighthouse Report
      uses: manrueda/lighthouse-report-action@v1.1.2
      with:
    # Directory where lighthouse JSON reports are stored
        reports: .lighthouseci
    # Github Token
        github-token: ${{ secrets.GITHUB_TOKEN }}
