name: Lighthouse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node Modules
      run: yarn

    - name: Build
      run: |
        yarn build

    - name: Lighthouse
      run: |
        yarn test:lh:ci --url=https://deploy-preview-${{ github.event.pull_request.number }}--friendly-mirzakhani-85ab7e.netlify.app/using-wpp-targets-file-together-sitecore/
        yarn test:lh:assert
  
    - name: Archive Lighthouse results
      uses: actions/upload-artifact@v1
      with:
        name: lighthouse-report
        path: .lighthouseci
