name: Lighthouse

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node Modules
      run: yarn

    - name: Build
      run: |
        yarn build

    - name: Lighthouse
      run: |
        yarn test:lh:ci --url=http://localhost:9000/using-wpp-targets-file-together-sitecore/
        yarn test:lh:assert
