name: Linting
on: [push]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Packages
        run: |
          yarn
      - name: Run Linting
        run: |
          yarn lint